Exit code 1 when base image has changed

diff --git a/.github/workflows/docker_image_update_checker.yml b/.github/workflows/docker_image_update_checker.yml
--- a/.github/workflows/docker_image_update_checker.yml
+++ b/.github/workflows/docker_image_update_checker.yml
@@ -7,25 +7,31 @@ name: 'DockerImageUpdateChecker'
 on:
   workflow_dispatch:
   schedule:
-    - cron: '40 11 * * *'
+    - cron: '4 8 * * *'
 
 jobs:
   CheckDockerImageUpdate:
     runs-on: 'ubuntu-latest'
     steps:
 
-      - name: Check if update available
+      -
+        # this step sets ${{ steps.check.outputs.needs-updating }}
+        name: Check whether base image was updated
         id: check
         uses: lucacome/docker-image-update-checker@v1
         with:
           base-image: perl:5.38-bookworm
           image: rotheross/otobo:latest-11_0
 
-      - name: Report the check result
+      -
+        # print the result in any case
+        name: Report the check result
         run: |
           echo "The OTOBO web image needs updating: ${{ steps.check.outputs.needs-updating }}"
 
-      - name: Notify that images need to be rebuilt
+      -
+        # indicate an error when the base image has changed
         if: steps.check.outputs.needs-updating == 'true'
         run: |
-          echo "::error:: Please update the latest OTOBO images for rel-10_0, rel-10_1. rel-11_0"
+          echo "::error:: Please update the latest OTOBO images for rel-10_0, rel-10_1. rel-11_0, and rel-11_1"
+          exit 1;
